# Generated by Django 3.0.6 on 2020-09-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Name')),
                ('generalAboutMe', models.TextField(default='About me')),
                ('image', models.FilePathField(path='img/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Name')),
                ('dateStarted', models.DateTimeField()),
                ('dateEnded', models.DateTimeField()),
                ('description', models.TextField(default='Experience Description')),
                ('image', models.FilePathField(path='img/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='home_page.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(default='List of skills')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home_page.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='School name')),
                ('dateStarted', models.DateTimeField()),
                ('dateEnded', models.DateTimeField()),
                ('description', models.TextField(default='School description')),
                ('image', models.FilePathField(path='img')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='home_page.Owner')),
            ],
        ),
    ]
