# Generated by Django 3.0.6 on 2020-09-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to='education_image'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(upload_to='owner_image'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='image',
            field=models.ImageField(upload_to='work_image'),
        ),
    ]
