# Generated by Django 3.0.6 on 2020-09-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20200913_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills',
        ),
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(default='', upload_to='skill_image'),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.TextField(default='Skill name'),
        ),
    ]
