# Generated by Django 3.0.6 on 2020-09-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20200914_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Application name')),
                ('image', models.ImageField(default='', upload_to='application_image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_application', to='home_page.Owner')),
            ],
        ),
    ]
