# Generated by Django 3.0.6 on 2020-09-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_programmingapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='skillsUsed',
            field=models.TextField(default='Skills used'),
        ),
    ]
