# Generated by Django 3.0.6 on 2020-09-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_workexperience_skillsused'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Title')),
                ('description', models.TextField(default='Description')),
                ('summary', models.TextField(default='Summary description')),
                ('programmingLanguages', models.TextField(default='Description')),
                ('image', models.ImageField(upload_to='project_image')),
            ],
        ),
    ]
